# Dockerfile.adaptor
FROM python:3.11-slim

WORKDIR /app
COPY adaptor.py /app/adaptor.py

# cài lib tối thiểu
RUN pip install --no-cache-dir kafka-python river numpy

# thư mục mount
RUN mkdir -p /data/snapshots /models

ENV RESULT_TOPIC=drift.results \
    MODEL_UPDATED_TOPIC=model.updated \
    KAFKA_BOOTSTRAP=kafka:9092 \
    GROUP_ID=adaptor-group \
    SNAPSHOT_DIR=/data/snapshots \
    MODEL_PATH=/models/current_model.pkl \
    TASK_TYPE=classification

CMD ["python", "-u", "adaptor.py"]
